'use client';
import {useState,useEffect,useMemo} from 'react';
import {RefreshCw,ArrowUpRight,Copy,Calculator,ChevronLeft,ChevronRight} from 'lucide-react';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell,TableCaption} from '@/components/ui/table';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectContent,SelectValue,SelectItem} from '@/components/ui/select';
import {type Coin,type Quote,type Conversion,type MoneyKey,quickCoins,convertToCents,quoteIsFresh,rateLabel,filterCoins,moneyKeys} from '@/lib/coins';
import {money} from '@/lib/profit';

type CatalogResult={coins:Coin[];fetchedAt:string};
let catalogRequest:Promise<CatalogResult>|null=null;let catalogExpires=0;
function getCatalog(){if(!catalogRequest||Date.now()>catalogExpires){catalogExpires=Date.now()+3600000;catalogRequest=fetch('/api/coins?mode=catalog').then(async r=>{const d=await r.json() as CatalogResult&{error?:string};if(!r.ok)throw Error(d.error);const popular=new Set(quickCoins.map(c=>c.id));return {...d,coins:[...quickCoins,...d.coins.filter(c=>!popular.has(c.id)).sort((a,b)=>a.name.localeCompare(b.name))]}}).catch(e=>{catalogRequest=null;throw e})}return catalogRequest}
function useCatalog(){const [coins,setCoins]=useState<Coin[]>(quickCoins),[loading,setLoading]=useState(true),[error,setError]=useState(''),[reload,setReload]=useState(0);useEffect(()=>{let active=true;setLoading(true);setError('');getCatalog().then(d=>{if(active)setCoins(d.coins)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Chưa tải được danh mục coin.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[reload]);return {coins,loading,error,retry:()=>{catalogRequest=null;setReload(n=>n+1)}}}
function useQuotes(ids:string[]){const key=[...new Set(ids)].sort().join(',');const [quotes,setQuotes]=useState<Record<string,Quote>>({}),[loading,setLoading]=useState(false),[error,setError]=useState(''),[reload,setReload]=useState(0);useEffect(()=>{if(!key)return;const controller=new AbortController();setLoading(true);setError('');setQuotes({});fetch('/api/coins?mode=prices&ids='+encodeURIComponent(key),{signal:controller.signal}).then(async r=>{const d=await r.json() as {quotes:Record<string,Quote>;error?:string};if(!r.ok)throw Error(d.error);if(!controller.signal.aborted)setQuotes(d.quotes)}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Không lấy được giá.')}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[key,reload]);return {quotes,loading,error,refresh:()=>setReload(n=>n+1)}}
function coinLabel(coin:Coin){return coin.symbol.toUpperCase()+' · '+coin.name}
function timeLabel(time:string){return new Date(time).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'})+' UTC+7'}
function CoinPicker({coins,coin,onChange}:{coins:Coin[];coin:Coin;onChange:(c:Coin)=>void}){const [query,setQuery]=useState('');const items=useMemo(()=>filterCoins(coins,query===coinLabel(coin)?'':query).slice(0,40),[coins,query,coin]);return <div className="coinpicker"><span className="fieldlabel">Coin</span><Combobox items={items} value={coin} onValueChange={v=>{if(v){onChange(v);setQuery('')}}} itemToStringLabel={coinLabel} isItemEqualToValue={(a,b)=>a.id===b.id} filter={null} onInputValueChange={v=>setQuery(v)}><ComboboxInput aria-label="Tìm coin theo tên hoặc ký hiệu" placeholder="Tìm ETH, SOL, MON hoặc tên coin…"/><ComboboxContent><ComboboxEmpty>Không tìm thấy coin. Thử tên đầy đủ.</ComboboxEmpty><ComboboxList>{(c:Coin)=><ComboboxItem key={c.id} value={c}><div><strong>{coinLabel(c)}</strong><small>ID: {c.id}</small></div></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><small>Đã chọn: {coinLabel(coin)} · ID: {coin.id}</small></div>}
export const conversionLabels:Record<MoneyKey,string>={incomeCents:'Tiền thu',costCents:'Vốn / chi phí',feeCents:'Phí'};

export function ConversionDetails({value}:{value:Conversion}){return <div className="conversiondetail"><strong>{value.amount} {value.symbol.toUpperCase()} = {money(value.usdCents)}</strong><span>1 {value.symbol.toUpperCase()} = {rateLabel(Number(value.rateUsd))} · {value.source==='manual'?'Giá tự nhập':'CoinGecko'}</span><small>{value.name} · ID: {value.coinId}<br/>{value.quotedAt?'Giá cập nhật: '+timeLabel(value.quotedAt):'Tỷ giá do bạn nhập'} · Lưu quy đổi: {timeLabel(value.capturedAt)}</small></div>}
function Converter({coin,setCoin,coins,amount,setAmount,onApply,buttonLabel}:{coin:Coin;setCoin:(c:Coin)=>void;coins:Coin[];amount:string;setAmount:(s:string)=>void;onApply:(c:Conversion)=>void;buttonLabel:string}){
 const market=useQuotes([coin.id]);const quote=market.quotes[coin.id];const [mode,setMode]=useState('market'),[manualRate,setManualRate]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{setMode('market');setManualRate('');setMessage('')},[coin.id]);
 const rate=mode==='manual'?manualRate:quote?.usd?.toString()??'';let cents:number|null=null,mathError='';try{cents=convertToCents(amount,rate)}catch(e){mathError=e instanceof Error?e.message:'Số không hợp lệ.'}
 const fresh=quoteIsFresh(quote);const usable=cents!==null&&(mode==='manual'||(fresh&&!market.loading&&!market.error));
 const text='Coin Calculator 💰\n1 '+coin.symbol.toUpperCase()+' = '+(rate&&Number(rate)>0?rateLabel(Number(rate)):'—')+'\n'+amount+' '+coin.symbol.toUpperCase()+' = '+(cents!==null?money(cents):'—')+'\n'+(mode==='manual'?'Tỷ giá tự nhập':quote?.updatedAt?'CoinGecko · '+timeLabel(quote.updatedAt):'Chưa có giá');
 return <section className="converter"><CoinPicker coins={coins} coin={coin} onChange={setCoin}/><div className="quickcoins">{quickCoins.slice(0,3).map(c=><button type="button" key={c.id} className={c.id===coin.id?'chosen':''} onClick={()=>setCoin(c)}>{c.symbol.toUpperCase()}</button>)}<a href={'https://www.coingecko.com/en/coins/'+encodeURIComponent(coin.id)} target="_blank" rel="noopener noreferrer">Xem coin <ArrowUpRight size={13}/></a></div><label>Số lượng {coin.symbol.toUpperCase()}<input type="text" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Ví dụ: 2.5"/></label><Tabs value={mode} onValueChange={v=>setMode(String(v))}><TabsList><TabsTrigger value="market">Giá thị trường</TabsTrigger><TabsTrigger value="manual">Tỷ giá tự nhập</TabsTrigger></TabsList></Tabs>
 {mode==='manual'?<label>Giá 1 {coin.symbol.toUpperCase()} (USD)<input type="text" inputMode="decimal" value={manualRate} onChange={e=>setManualRate(e.target.value)} placeholder="Giá tại thời điểm bạn giao dịch"/></label>:<div className="quoteline"><span>{market.loading?'Đang lấy giá…':quote?.usd?<>1 {coin.symbol.toUpperCase()} = <b>{rateLabel(quote.usd)}</b></>:'Chưa có giá cho coin này'}</span><button type="button" className="iconbutton" onClick={market.refresh} disabled={market.loading} aria-label="Lấy lại giá coin"><RefreshCw size={16}/></button></div>}
 {mode==='market'&&market.error&&<p role="alert" className="coinerror">{market.error}</p>}
 {mode==='market'&&quote?.usd&&!fresh&&<p className="coinerror">Giá đã cũ hoặc chưa có thời điểm cập nhật. Lấy lại giá hoặc dùng tỷ giá tự nhập để tiếp tục.</p>}
 <div className="coinresult"><span>{amount||'0'} {coin.symbol.toUpperCase()}</span><strong>{cents!==null?money(cents):'—'}</strong><small>{mode==='manual'?'Theo tỷ giá bạn nhập':quote?.updatedAt?'Giá cập nhật: '+timeLabel(quote.updatedAt):'Đang chờ giá thị trường'}</small></div>
 {mathError&&amount&&rate&&<p className="coinerror">{mathError}</p>}
 <p className="coinhint">Tính theo tỷ giá đầy đủ, làm tròn USD đến cent. Giao dịch cũ: chọn tỷ giá tự nhập tại thời điểm giao dịch.</p>
 <div className="converteractions"><button type="button" className="action primary" disabled={!usable} onClick={()=>{if(!usable||cents===null)return;if(mode==='market'&&!quoteIsFresh(quote)){setMessage('Giá đã cũ. Bấm lấy lại giá trước khi áp dụng.');return}onApply({coinId:coin.id,symbol:coin.symbol,name:coin.name,amount,rateUsd:rate,usdCents:cents,source:mode==='manual'?'manual':'CoinGecko',quotedAt:mode==='manual'?null:quote?.updatedAt??null,capturedAt:new Date().toISOString()})}}><Calculator size={16}/>{buttonLabel}</button><button type="button" className="textbutton" disabled={!usable} onClick={async()=>{try{await navigator.clipboard.writeText(text);setMessage('Đã sao chép kết quả.')}catch{setMessage('Chưa sao chép được. Bạn có thể chọn kết quả và sao chép thủ công.')}}}><Copy size={15}/> Sao chép</button></div>{message&&<p role="status" className="coinhint">{message}</p>}
 </section>
}

export function ProfitConversion({onApply}:{onApply:(key:MoneyKey,c:Conversion)=>void}){const catalog=useCatalog(),[coin,setCoin]=useState(quickCoins[0]),[amount,setAmount]=useState('1'),[target,setTarget]=useState<MoneyKey>('incomeCents'),[applied,setApplied]=useState('');return <div className="profitconversion"><h3>Quy đổi coin sang USD</h3><div className="conversiontarget"><span>Điền vào</span><Select value={target} onValueChange={v=>{if(v)setTarget(v as MoneyKey)}}><SelectTrigger aria-label="Khoản cần quy đổi"><SelectValue/></SelectTrigger><SelectContent>{moneyKeys.map(k=><SelectItem key={k} value={k}>{conversionLabels[k]}</SelectItem>)}</SelectContent></Select></div>{catalog.error&&<p className="coinerror">{catalog.error} <button type="button" onClick={catalog.retry}>Thử lại danh mục</button></p>}<Converter coins={catalog.coins} coin={coin} setCoin={setCoin} amount={amount} setAmount={setAmount} buttonLabel={'Áp dụng vào '+conversionLabels[target].toLowerCase()} onApply={c=>{onApply(target,c);setApplied('Đã điền '+conversionLabels[target].toLowerCase()+'. Bấm Lưu khoản profit để lưu giao dịch.')}}/>{applied&&<p role="status" className="positive coinhint">{applied}</p>}</div>}

export default function CoinCalculator({onCreateProfit}:{onCreateProfit:(c:Conversion)=>void}){
 const catalog=useCatalog();const [coin,setCoin]=useState<Coin>(quickCoins[0]),[amount,setAmount]=useState('1'),[search,setSearch]=useState(''),[page,setPage]=useState(0),[amounts,setAmounts]=useState<Record<string,string>>({});
 const filtered=useMemo(()=>filterCoins(catalog.coins,search),[catalog.coins,search]);const pageSize=25;const pages=Math.max(1,Math.ceil(filtered.length/pageSize));const safePage=Math.min(page,pages-1);const visible=filtered.slice(safePage*pageSize,(safePage+1)*pageSize);const market=useQuotes(visible.map(c=>c.id));
 return <><div className="viewheading"><div><h2>Coin Calculator 💰</h2><p className="subtle">Quy đổi coin → USD · Lưu kết quả vào Profit Tracker</p></div><a className="textbutton" href="https://www.coingecko.com/" target="_blank" rel="noopener noreferrer">Dữ liệu: CoinGecko ↗</a></div><div className="coingrid"><div className="panel"><Converter coins={catalog.coins} coin={coin} setCoin={setCoin} amount={amount} setAmount={setAmount} onApply={onCreateProfit} buttonLabel="Tạo nháp profit từ kết quả"/></div><aside className="panel coinhow"><p className="eyebrow">COIN → USD → PROFIT</p><h2>Nhận SOL, ghi profit bằng USD.</h2><p>Chọn đúng coin, nhập số lượng bạn nhận. Kết quả có thể điền vào tiền thu của một nháp profit.</p><p>Trong mỗi khoản profit, bạn có thể quy đổi riêng tiền thu, vốn và phí bằng các coin khác nhau.</p><p>Giá và số lượng được lưu cùng giao dịch. Profit đã ghi không chạy theo giá thị trường về sau.</p><div className="coincoverage"><strong>{catalog.loading?'Đang tải danh mục…':catalog.error?'Danh mục chưa tải đầy đủ':catalog.coins.length.toLocaleString('vi-VN')+' coin'}</strong><span>Các coin trong danh mục CoinGecko; không bao gồm mọi token trên DEX.</span></div></aside></div>
 <section className="panel coinmarket"><div className="panelheading"><h2>Bảng tính coin</h2><button type="button" className="action" disabled={market.loading} onClick={market.refresh}><RefreshCw size={15}/> Cập nhật giá</button></div><label className="marketsearch">Tìm toàn bộ danh mục<input value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}} placeholder="Tên coin, ticker hoặc CoinGecko ID…"/></label>{catalog.error&&<p role="alert" className="coinerror">{catalog.error} <button type="button" className="textbutton" onClick={catalog.retry}>Tải lại danh mục</button></p>}{market.error&&<p role="alert" className="coinerror">{market.error}</p>}
 <Table className="cointable"><TableCaption>Giá có thể được lưu đệm 60 giây. Coin chưa có giá hiển thị “—”; giá cũ được đánh dấu. Số lượng ở bảng là phép tính tạm, chỉ được lưu khi bạn lưu khoản profit.</TableCaption><TableHeader><TableRow><TableHead>Coin / ID</TableHead><TableHead>Giá 1 coin</TableHead><TableHead>24h</TableHead><TableHead>Số lượng</TableHead><TableHead>Giá trị USD</TableHead><TableHead><span className="sr-only">Chọn</span></TableHead></TableRow></TableHeader><TableBody>{visible.map(c=>{const q=market.quotes[c.id],qty=amounts[c.id]??'1';let total:number|null=null;try{if(q?.usd)total=convertToCents(qty,q.usd.toString())}catch{}return <TableRow key={c.id}><TableCell><button type="button" className="coinname" onClick={()=>{setCoin(c);setAmount(qty)}}><strong>{c.symbol.toUpperCase()} <span>{c.name}</span></strong><small>{c.id}</small></button></TableCell><TableCell>{market.loading?'…':q?.usd?rateLabel(q.usd):'—'}{q?.usd&&!quoteIsFresh(q)&&<small className="coinerror block">Giá cũ</small>}</TableCell><TableCell className={(q?.change24h??0)<0?'negative':'positive'}>{q?.change24h!=null?q.change24h.toFixed(2)+'%':'—'}</TableCell><TableCell><input aria-label={'Số lượng '+c.name} className="rowquantity" type="text" inputMode="decimal" value={qty} onChange={e=>setAmounts(prev=>({...prev,[c.id]:e.target.value}))}/></TableCell><TableCell>{total!==null?money(total):'—'}</TableCell><TableCell><button type="button" className="textbutton" onClick={()=>{setCoin(c);setAmount(qty);document.getElementById('coin-calculator-top')?.scrollIntoView({behavior:'smooth',block:'start'})}}>Tính ↗</button></TableCell></TableRow>})}</TableBody></Table>
 {!visible.length&&<div className="empty">Không tìm thấy coin. Thử tên đầy đủ hoặc ID.</div>}<div className="coinpagination"><span>{filtered.length.toLocaleString('vi-VN')} kết quả · Trang {safePage+1}/{pages}</span><button type="button" className="iconbutton" aria-label="Trang coin trước" disabled={safePage===0} onClick={()=>setPage(safePage-1)}><ChevronLeft size={18}/></button><button type="button" className="iconbutton" aria-label="Trang coin sau" disabled={safePage>=pages-1} onClick={()=>setPage(safePage+1)}><ChevronRight size={18}/></button></div></section></>
}
