'use client';
import {useState,useRef,useEffect} from 'react';
import {Plus,Pencil,ArrowUpRight} from 'lucide-react';
import {Table,TableHeader,TableBody,TableHead,TableCell,TableRow,TableCaption} from '@/components/ui/table';
import {Select,SelectTrigger,SelectContent,SelectValue,SelectItem} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {type Entry,profitCategories} from '@/lib/model';
import {type Period,periods,money,net,inPeriod,profitTotals,parseUsd} from '@/lib/profit';

export function MoneyField({label,cents,onChange}:{label:string;cents:number;onChange:(n:number)=>void}){
 const [value,setValue]=useState((cents/100).toFixed(2));const lastInput=useRef(cents);
 useEffect(()=>{if(!Object.is(cents,lastInput.current)){lastInput.current=cents;setValue(Number.isFinite(cents)?(cents/100).toFixed(2):'')}},[cents]);
 return <label>{label}<input type="text" inputMode="decimal" required pattern="[0-9]+([.][0-9]{1,2})?" title="Nhập USD với tối đa 2 số thập phân, ví dụ 12.50" value={value} onChange={e=>{setValue(e.target.value);lastInput.current=parseUsd(e.target.value);onChange(lastInput.current)}}/></label>
}
export default function ProfitPanel({records,date,create,edit,loading}:{records:Entry[];date:string;create:()=>void;edit:(e:Entry)=>void;loading:boolean}){
 const [period,setPeriod]=useState<Period>('Tháng');const [category,setCategory]=useState('Tất cả');
 const all=records.filter(r=>r.kind==='profit');
 const selected=all.filter(r=>inPeriod(r.date,date,period)&&(category==='Tất cả'||r.category===category));
 const totals=profitTotals(selected);const open=all.filter(r=>r.status==='Chưa chốt'&&(category==='Tất cả'||r.category===category));
 const list=[...selected].sort((a,b)=>b.date.localeCompare(a.date));
 return <><div className="viewheading"><div><h2>Profit Tracker</h2><p className="subtle">NFT · Airdrop · Trade · Công việc Web3</p></div><button className="action primary" onClick={create}><Plus size={17}/> Thêm khoản profit</button></div>
 <div className="profitfilters"><Tabs value={period} onValueChange={v=>setPeriod(v as Period)}><TabsList>{periods.map(p=><TabsTrigger key={p} value={p}>{p}</TabsTrigger>)}</TabsList></Tabs><span className="subtle">{period==='Tất cả'?'Toàn bộ lịch sử':'Theo ngày đang chọn: '+date}</span><Select value={category} onValueChange={v=>{if(v)setCategory(v)}}><SelectTrigger aria-label="Nguồn profit"><SelectValue/></SelectTrigger><SelectContent>{['Tất cả',...profitCategories].map(c=><SelectItem value={c} key={c}>{c}</SelectItem>)}</SelectContent></Select></div>
 <div className="profitstats"><article className="profitmain"><span>PROFIT ĐÃ CHỐT · USD</span><strong className={totals.profit<0?'negative':'positive'}>{loading?'…':money(totals.profit)}</strong><p>{totals.count} khoản đã chốt · {totals.roi===null?'ROI — (chưa có vốn / phí)':`ROI ${totals.roi.toFixed(2)}%`}</p></article><article><span>Tiền thu</span><strong>{money(totals.income)}</strong><small>Các khoản đã chốt trong kỳ</small></article><article><span>Vốn + chi phí</span><strong>{money(totals.cost)}</strong><small>Giá vốn tương ứng khoản đã chốt</small></article><article><span>Phí</span><strong>{money(totals.fees)}</strong><small>Gas, giao dịch, nền tảng…</small></article></div>
 <p className="profitexplain">Profit = tiền thu − vốn − phí. Nhập USD hoặc quy đổi từ coin trong từng khoản profit. Tỷ giá được giữ nguyên sau khi lưu. Khoản chưa chốt không được cộng vào profit.</p>
 <div className="profitbreakdown">{profitCategories.filter(c=>category==='Tất cả'||c===category).map(c=>{const t=profitTotals(selected.filter(r=>r.category===c));return <article key={c}><span>{c}</span><strong className={t.profit<0?'negative':'positive'}>{money(t.profit)}</strong><small>{t.count} khoản đã chốt</small></article>})}</div>
 <section className="panel"><div className="panelheading"><h2>Sổ profit <span className="subtle">· {list.length} khoản trong kỳ</span></h2></div>{list.length?<Table className="profittable"><TableCaption>Ngày là ngày chốt; với khoản chưa chốt, đây là ngày bắt đầu theo dõi.</TableCaption><TableHeader><TableRow><TableHead>Ngày / dự án</TableHead><TableHead>Nguồn</TableHead><TableHead>Tiền thu</TableHead><TableHead>Vốn + phí</TableHead><TableHead>Profit</TableHead><TableHead>Trạng thái</TableHead><TableHead><span className="sr-only">Chỉnh sửa</span></TableHead></TableRow></TableHeader><TableBody>{list.map(r=><TableRow key={r.id}><TableCell><button onClick={()=>edit({...r})} className="profitproject"><strong>{r.title}</strong><span>{r.date}{r.chain?' · '+r.chain:''}</span></button></TableCell><TableCell>{r.category}</TableCell><TableCell>{money(r.incomeCents??0)}{r.conversions?.incomeCents&&<small className="ledgercoin">{r.conversions.incomeCents.amount} {r.conversions.incomeCents.symbol.toUpperCase()}</small>}</TableCell><TableCell>{money((r.costCents??0)+(r.feeCents??0))}</TableCell><TableCell className={r.status==='Đã chốt'?(net(r)<0?'negative':'positive'):''}>{r.status==='Đã chốt'?money(net(r)):'—'}</TableCell><TableCell><span className={'pill '+(r.status==='Đã chốt'?'green':'')}>{r.status}</span></TableCell><TableCell><button className="iconbutton" onClick={()=>edit({...r})} aria-label={'Sửa profit '+r.title}><Pencil size={16}/></button>{r.url&&<a className="iconbutton" href={r.url} target="_blank" rel="noopener noreferrer" aria-label={'Mở giao dịch '+r.title}><ArrowUpRight size={16}/></a>}</TableCell></TableRow>)}</TableBody></Table>:<div className="empty">Chưa có khoản profit trong kỳ này.<br/>Thêm giao dịch hoặc thu nhập đầu tiên để bắt đầu.</div>}</section>
 <section className="panel openprofit"><div><h2>Đang theo dõi · {open.length} khoản chưa chốt</h2><p className="subtle">Toàn bộ thời gian{category!=='Tất cả'?' · '+category:''}. Cập nhật ngày chốt, tiền thu và vốn tương ứng khi hoàn tất.</p></div><strong>{money(open.reduce((s,r)=>s+(r.costCents??0)+(r.feeCents??0),0))}<small>Vốn + phí đã nhập</small></strong>{open.length>0&&<div className="openprofitlist">{open.map(r=><button key={r.id} className="textbutton" onClick={()=>edit({...r})}>{r.title} <Pencil size={14}/></button>)}</div>}</section>
 </>
}
